<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PhotoManager.Domain\PhotoManager.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
